### ISSUE TITLE
node_modules should be out of git

### ISSUE THREAD

**Issue by alessioalex** [angularjs-de/angularjs-de-seed-es6#1]
they are >= 180 Mb :(

**Comment by alessioalex** [comment]
instead of having them in git for lockdown there's a better solution: https://docs.npmjs.com/cli/shrinkwrap

**Comment by robinboehm** [comment]
+1
0843aaffd4c43f88ba45b9be449ab6372d8a3abb
thanks :)

**Comment by alessioalex** [comment]
hey @robinboehm maybe it would be best to remove them from the whole git history, like this guy did here: http://dalibornasevic.com/posts/2-permanently-remove-files-and-folders-from-git-repo

even though you did remove them with the latest commit, they are still included in the history and thus the big download problem will still occur.

cheers!

**Comment by robinboehm** [comment]
Yeah I know - it's already on my todo :)
Thx 

Liebe Grüße
Robin Böhm

Send from mobile
